export default {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  INPUT_CHANGED: 'INPUT_CHANGED',
  LIST_ITEM: 'LIST_ITEM',
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  SEARCH_INPUT: 'SEARCH_INPUT',
  GET_REPO: 'GET_REPO'
}